version: "3"
services:
  poc-agenda:
    image: poc-agenda
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      MONGO_DB_URL: mongodb://mongo:27017/poc-agenda
    depends_on:
      - mongo
  agendash:
    image: agenda/agendash
    ports:
      - "3001:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/poc-agenda
      COLLECTION: agendaJobs
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_conf:/data/configdb
volumes:
  mongo_data:
  mongo_conf:
